### ISSUE TITLE
coq-8.11.2-1: ocamlfind version mismatch

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1074] opened 2023-10-04 12:40 UTC
```
./configure -prefix /opt/sw -libdir /opt/sw/lib/ocaml/coq -coqdocdir /opt/sw/share/doc/coq -mandir /opt/sw/share/man -coqide no -with-doc no -browser 'open %s'
You have OCaml 4.12.0. Good!
Your version of OCamlfind is 1.3.3.
You need OCamlfind 1.4.1 or later.
Configuration script failed!
### execution of ./configure failed, exit code 1
### execution of /tmp/fink.QR80U failed, exit code 1
Removing runtime build-lock...
Removing build-lock package...
/opt/sw/bin/dpkg-lockwait -r fink-buildlock-coq-8.11.2-1
(Reading database ... 
dpkg: serious warning: files list file for package `fink-buildlock-ccp4-6.5-1' missing, assuming package has no files currently installed.
1042039 files and directories currently installed.)
Removing fink-buildlock-coq-8.11.2-1 ...
```
`ocamlfind` comes from package `ocaml-findlib`:
```
$ /opt/sw/bin/dpkg -S /opt/sw/bin/ocamlfind
dpkg: serious warning: files list file for package `fink-buildlock-ccp4-6.5-1' missing, assuming package has no files currently installed.
ocaml-findlib: /opt/sw/bin/ocamlfind
```
Unfortunately, trying to upgrade `ocaml-findlib` fails due to a conflict with `ocamlbuild` over `/opt/sw/lib/ocaml/ocamlbuild/META`:
```
$ fink install ocaml-findlib
Information about 15256 packages read in 2 seconds.
The package 'ocaml-findlib' will be installed.
Reading dependency for ocaml-findlib-1.9.1-2...
Reading runtime dependency for ocaml-findlib-1.9.1-2...
The following package will be installed or updated:
 ocaml-findlib
Reading buildlock packages...
	All buildlocks accounted for.
/opt/sw/bin/dpkg-lockwait -i /opt/sw/fink/dists/stable/main/binary-darwin-x86_64/libs/ocamlmods/ocaml-findlib_1.9.1-2_darwin-x86_64.deb
(Reading database ... 
dpkg: serious warning: files list file for package `fink-buildlock-ccp4-6.5-1' missing, assuming package has no files currently installed.
1042038 files and directories currently installed.)
Preparing to replace ocaml-findlib 1.3.3-2 (using .../ocaml-findlib_1.9.1-2_darwin-x86_64.deb) ...

    You must first install ccp4-6.5 from http://www.ccp4.ac.uk/download
    It supercedes the fink version as it now posesses its own internal package management system.

    If you have installed ccp4-6.5 in a non-canonical location, you must edit this file. 

    Please check that ccp4-6.5 is the right ccp4 version.


    You must first install ccp4-6.5 from http://www.ccp4.ac.uk/download
    It supercedes the fink version as it now posesses its own internal package management system.

    If you have installed ccp4-6.5 in a non-canonical location, you must edit this file. 

    Please check that ccp4-6.5 is the right ccp4 version.

Unpacking replacement ocaml-findlib ...
/opt/sw/bin/dpkg: error processing /opt/sw/fink/dists/stable/main/binary-darwin-x86_64/libs/ocamlmods/ocaml-findlib_1.9.1-2_darwin-x86_64.deb (--install):
 trying to overwrite `/opt/sw/lib/ocaml/ocamlbuild/META', which is also in package ocamlbuild
/opt/sw/bin/dpkg-deb: subprocess paste killed by signal (Broken pipe: 13)

    You must first install ccp4-6.5 from http://www.ccp4.ac.uk/download
    It supercedes the fink version as it now posesses its own internal package management system.

    If you have installed ccp4-6.5 in a non-canonical location, you must edit this file. 

    Please check that ccp4-6.5 is the right ccp4 version.


    You must first install ccp4-6.5 from http://www.ccp4.ac.uk/download
    It supercedes the fink version as it now posesses its own internal package management system.

    If you have installed ccp4-6.5 in a non-canonical location, you must edit this file. 

    Please check that ccp4-6.5 is the right ccp4 version.

Errors were encountered while processing:
 /opt/sw/fink/dists/stable/main/binary-darwin-x86_64/libs/ocamlmods/ocaml-findlib_1.9.1-2_darwin-x86_64.deb
### execution of /opt/sw/bin/dpkg-lockwait failed, exit code 1
Failed: can't install package ocaml-findlib-1.9.1-2
```

**Comment by cooljeanius** [comment] 2023-10-04 12:43
Is Heejong Lee (maintainer listed for ocaml-findlib) @HeejongLee-aws or @ihji?

**Comment by TheSin-** [comment] 2023-10-04 13:32
duplicate of #880

**Comment by cooljeanius** [comment] 2023-10-04 20:02
> duplicate of #880

Ah, so it is; I only thought to search for "coq" first before filing this one...

**Closed** 2023-10-04 20:03 UTC
