### ISSUE TITLE
gsasl19 does not build on macOS 15 / Xcode 16

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#1185] opened 2024-11-12 02:35 UTC
Has error in defining attribute list.    Final definition "static [[_maybe_unused__]] bool
Not sure how to fix this.

In file included from c-ctype.c:21:
./c-ctype.h:259:1: error: an attribute list cannot appear here
  259 | C_CTYPE_INLINE bool
      | ^~~~~~~~~~~~~~
c-ctype.c:20:24: note: expanded from macro 'C_CTYPE_INLINE'
   20 | #define C_CTYPE_INLINE _GL_EXTERN_INLINE
      |                        ^~~~~~~~~~~~~~~~~
../../config.h:2096:35: note: expanded from macro '_GL_EXTERN_INLINE'
 2096 | # define _GL_EXTERN_INLINE static _GL_UNUSED
      |                                   ^~~~~~~~~~
../../config.h:1846:20: note: expanded from macro '_GL_UNUSED'
 1846 | #define _GL_UNUSED _GL_ATTRIBUTE_MAYBE_UNUSED
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../config.h:1836:40: note: expanded from macro '_GL_ATTRIBUTE_MAYBE_UNUSED'
 1836 | #    define _GL_ATTRIBUTE_MAYBE_UNUSED [[__maybe_unused__]]

**Comment by nieder** [comment] 2024-11-12 10:03
duplicate of #1177

**Closed by nieder** 2024-11-12 10:03 UTC
Labels: bug
